helloworld/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth.views import login, logout

from core import views

urlpatterns = [
    # URL padrão
    path('', views.index, name='index'),
    path('entrar/', login, {'template_name':'accounts/login.html'}, name='login'),
    path('sair/', logout, {'next_page':'index'}, name='logout'),
    path('conta/', include('accounts.urls')),
    path('website/', include('website.urls')),
    # Interface administrativa
    path('admin/', admin.site.urls),
]

website/urls.py
from website.views import (IndexTemplateView, ComercioListView,
    ComercioCreateView, ComercioUpdateView, ComercioDeleteView,
    GastoListView, GastoCreateView, GastoUpdateView,
    GastoDeleteView, GastoComercioListView)

from django.urls import path

app_name = "website"

urlpatterns = [
    path('',IndexTemplateView.as_view(),name="index"),
    path('gastos/',GastoListView.as_view(),name="lista_gastos"),
    path('gastosPorComercio/<slug>/',GastoComercioListView.as_view(),name="lista_gastosPorComercio"),
    path('gasto/cadastrar',GastoCreateView.as_view(),name="cadastra_gasto"),
    path('gasto/<pk>',GastoUpdateView.as_view(),name="atualiza_gasto"),
    path('gasto/excluir/<pk>',GastoDeleteView.as_view(),name="deleta_gasto"),
    path('comercios/',ComercioListView.as_view(),name="lista_comercios"),
    path('comercio/cadastrar',ComercioCreateView.as_view(),name="cadastra_comercio"),
    path('comercio/<slug>',ComercioUpdateView.as_view(),name="atualiza_comercio"),
    path('comercio/excluir/<slug>',ComercioDeleteView.as_view(),name="deleta_comercio"),
]

website/models.py
# coding=utf-8

from django.db import models
import datetime
from django.urls import reverse

class Comercio(models.Model):

    name = models.CharField('Comercio',max_length=100,null=False,blank=False)
    slug = models.SlugField('Identificador', max_length=100)
    created_at = models.DateTimeField('Criado em',auto_now_add=True,null=True)
    updated_at = models.DateTimeField('Atualizado em',auto_now=True,null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Comércio'
        verbose_name_plural = 'Comércios'
        ordering = ['-created_at']

    def get_absolute_url(self):
        return reverse('website:lista_gastosPorComercio', kwargs={'slug': self.slug})

    objetos = models.Manager()

class Gasto(models.Model):

    name = models.CharField('Gastos',max_length=100,null=False,blank=False)
    slug = models.SlugField('Identificador', max_length=100)
    valor = models.CharField(max_length=100,null=False,blank=False)
    datagasto = models.DateField(default=datetime.datetime.today,null=True,blank=True)
    comercio = models.ForeignKey(Comercio,verbose_name='Comércio',on_delete=models.PROTECT)
    created_at = models.DateTimeField('Criado em',auto_now_add=True,null=True)
    modified_at = models.DateTimeField('Atualizado em',auto_now=True,null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Gasto'
        verbose_name_plural = 'Gastos'
        ordering = ['-datagasto']

    objetos = models.Manager()

website/forms.py
from .models import Comercio, Gasto
from django import forms
from django.contrib.admin import widgets
# from dal import autocomplete


# FORMULÁRIO DE INCLUSÃO DE GASTOS
# -------------------------------------------

class InsereGastoForm(forms.ModelForm):

    chefe = forms.BooleanField(
        label='Chefe?',
        required=False,
    )

    biografia = forms.CharField(
        label='Biografia',
        required=False,
        widget=forms.Textarea
    )

    datagasto = forms.DateField(widget=widgets.AdminDateWidget)


    class Meta:
        # Modelo base
        model = Gasto

        # Campos que estarão no form
        fields = [
            'name',
            'slug',
            'valor',
            'datagasto',
            'comercio'
        ]


# FORMULÁRIO DE INCLUSÃO DE COMÉRCIOS
# -------------------------------------------

class InsereComercioForm(forms.ModelForm):

    chefe = forms.BooleanField(
        label='Chefe?',
        required=False,
    )

    biografia = forms.CharField(
        label='Biografia',
        required=False,
        widget=forms.Textarea
    )

    class Meta:
        # Modelo base
        model = Comercio

        # Campos que estarão no form
        fields = [
            'name',
            'slug'
        ]

website/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from .models import Comercio, Gasto
from website.forms import InsereComercioForm, InsereGastoForm
from django.contrib.auth.mixins import LoginRequiredMixin


# PÁGINA PRINCIPAL
# ----------------------------------------------

class IndexTemplateView(LoginRequiredMixin, generic.TemplateView):
    template_name = "index.html"

# LISTA DE GASTOS
# ----------------------------------------------

class GastoListView(LoginRequiredMixin, generic.ListView):
    template_name = "website/lista_gastos.html"
    model = Gasto
    context_object_name = "gastos"
    paginate_by = 5

# LISTA DE GASTOS DE UM COMÉRCIO ESPECÍFICO
# ----------------------------------------------

class GastoComercioListView(LoginRequiredMixin, generic.ListView):

    template_name = "website/lista_gastosPorComercio.html"
    context_object_name = "gastos"
    paginate_by = 5

    def get_queryset(self):
        return Gasto.objetos.filter(comercio__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(GastoComercioListView, self).get_context_data(**kwargs)
        context['current_comercio'] = get_object_or_404(Comercio, slug=self.kwargs['slug'])
        return context

gastoComercio = GastoComercioListView.as_view()

# CADASTRAMENTO DE GASTOS
# ----------------------------------------------

class GastoCreateView(generic.CreateView):
    template_name = "website/cria_gasto.html"
    model = Gasto
    form_class = InsereGastoForm
    success_url = reverse_lazy("website:lista_gastos")

# ATUALIZAÇÃO DE GASTOS
# ----------------------------------------------

class GastoUpdateView(generic.UpdateView):
    template_name = "website/atualiza_gasto.html"
    model = Gasto
    fields = '__all__'
    context_object_name = 'gasto'
    success_url = reverse_lazy("website:lista_gastos")

    def get_object(self, queryset=None):
      gasto = None

      # Se você utilizar o debug, verá que os
      # campos {pk} e {slug} estão presente em self.kwargs
      id = self.kwargs.get(self.pk_url_kwarg)
      slug = self.kwargs.get(self.slug_url_kwarg)

      if id is not None:
        # Busca o gasto apartir do id
        gasto = Gasto.objetos.filter(id=id).first()

      elif slug is not None:
        # Pega o campo slug do Model
        campo_slug = self.get_slug_field()

        # Busca o gasto apartir do slug
        gasto = Gasto.objetos.filter(**{campo_slug: slug}).first()

      # Retorna o objeto encontrado
      return gasto

# EXCLUSÃO DE GASTOS
# ----------------------------------------------

class GastoDeleteView(generic.DeleteView):
    template_name = "website/exclui_gasto.html"
    model = Gasto
    fields = '__all__'
    context_object_name = 'gasto'
    success_url = reverse_lazy("website:lista_gastos")

# LISTA DE COMÉRCIOS
# ----------------------------------------------

class ComercioListView(LoginRequiredMixin, generic.ListView):
    template_name = "website/lista_comercios.html"
    model = Comercio
    context_object_name = "comercios"
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super(ComercioListView, self).get_context_data(**kwargs)
        list_exam = Comercio.objetos.all()
        paginator = Paginator(list_exam, self.paginate_by)

        page = self.request.GET.get('page')

        try:
            file_exams = paginator.page(page)
        except PageNotAnInteger:
            file_exams = paginator.page(1)
        except EmptyPage:
            file_exams = paginator.page(paginator.num_pages)

        context['list_exams'] = file_exams
        return context

# CADASTRAMENTO DE COMÉRCIOS
# ----------------------------------------------

class ComercioCreateView(generic.CreateView):
    template_name = "website/cria_comercio.html"
    model = Comercio
    form_class = InsereComercioForm
    success_url = reverse_lazy("website:lista_comercios")

# ATUALIZAÇÃO DE COMÉRCIOS
# ----------------------------------------------

class ComercioUpdateView(generic.UpdateView):
    template_name = "website/atualiza_comercio.html"
    model = Comercio
    fields = '__all__'
    context_object_name = 'comercio'
    success_url = reverse_lazy("website:lista_comercios")

    def get_object(self, queryset=None):
      comercio = None

      # Se você utilizar o debug, verá que os
      # campos {pk} e {slug} estão presente em self.kwargs
      id = self.kwargs.get(self.pk_url_kwarg)
      slug = self.kwargs.get(self.slug_url_kwarg)

      if id is not None:
        # Busca o comercio apartir do id
        comercio = Comercio.objects.filter(id=id).first()

      elif slug is not None:
        # Pega o campo slug do Model
        campo_slug = self.get_slug_field()

        # Busca o comercio apartir do slug
        comercio = Comercio.objetos.filter(**{campo_slug: slug}).first()

      # Retorna o objeto encontrado
      return comercio

# EXCLUSÃO DE COMÉRCIOS
# ----------------------------------------------

class ComercioDeleteView(generic.DeleteView):
    template_name = "website/exclui_comercio.html"
    model = Comercio
    fields = '__all__'
    context_object_name = 'comercio'
    success_url = reverse_lazy("website:lista_comercios")

    def get_object(self, queryset=None):
      comercio = None

      # Se você utilizar o debug, verá que os
      # campos {pk} e {slug} estão presente em self.kwargs
      id = self.kwargs.get(self.pk_url_kwarg)
      slug = self.kwargs.get(self.slug_url_kwarg)

      if id is not None:
        # Busca o comercio apartir do id
        comercio = Comercio.objects.filter(id=id).first()

      elif slug is not None:
        # Pega o campo slug do Model
        campo_slug = self.get_slug_field()

        # Busca o comercio apartir do slug
        comercio = Comercio.objetos.filter(**{campo_slug: slug}).first()

      # Retorna o objeto encontrado
      return comercio

website/templates/website/atualiza.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Dados do Funcionários{% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualização de Dados do Funcionário</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- Sobrenome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Sobrenome</span>
              </div>
              {% render_field form.sobrenome class+="form-control" %}
            </div>

            <!-- CPF -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">CPF</span>
              </div>
              {% render_field form.cpf class+="form-control" %}
            </div>

            <!-- Tempo de Serviço -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Tempo de Serviço</span>
              </div>
              {% render_field form.tempo_de_servico class+="form-control" %}
            </div>

            <!-- Remuneração -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Remuneração</span>
              </div>
              {% render_field form.remuneracao class+="form-control" %}
            </div>

            <button class="btn btn-primary">Enviar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/atualiza_comercio.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Dados do Comércios{% endblock %}

{% block conteudo %}
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualização de Dados do Comércio</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.name class+="form-control" %}
            </div>

            <!-- Slug -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Identificador</span>
              </div>
              {% render_field form.slug class+="form-control" %}
            </div>

            <button class="btn btn-primary">Enviar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/website/atualiza_gasto.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Atualização de Dados do Gastos{% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Atualização de Dados do Gasto</h5>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.name class+="form-control" %}
            </div>

            <!-- Slug -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Identificador</span>
              </div>
              {% render_field form.slug class+="form-control" %}
            </div>

            <!-- Valor -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Valor</span>
              </div>
              {% render_field form.valor class+="form-control" %}
            </div>

            <!-- Datagasto -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Data Gasto</span>
              </div>
              {% render_field form.datagasto class+="form-control" %}
            </div>
            </div>

            <!-- Comercio -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Comércio</span>
              </div>
              {% render_field form.comercio class+="form-control" %}
            </div>

            <button class="btn btn-primary">Enviar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/cria.html
{% extends "website/_layouts/base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Funcionários{% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastro de Funcionário</h5>
          <p class="card-text">
            Complete o formulário abaixo para cadastrar
            um novo <code>Funcionário</code>.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.nome class+="form-control" %}
            </div>

            <!-- Sobrenome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Sobrenome</span>
              </div>
              {% render_field form.sobrenome class+="form-control" %}
            </div>

            <!-- CPF -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">CPF</span>
              </div>
              {% render_field form.cpf class+="form-control" %}
            </div>

            <!-- Tempo de Serviço -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Tempo de Serviço</span>
              </div>
              {% render_field form.tempo_de_servico class+="form-control" %}
            </div>

            <!-- Remuneração -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Remuneração</span>
              </div>
              {% render_field form.remuneracao class+="form-control" %}
            </div>

            <button class="btn btn-primary">Enviar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/cria_comercio.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Cadastro de Comércios{% endblock %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Cadastro de Comércio</h5>
          <p class="card-text">
            Complete o formulário abaixo para cadastrar
            um novo <code>Comércio</code>.
          </p>
          <form method="post">
            <!-- Não se esqueça dessa tag -->
            {% csrf_token %}

            <!-- Nome -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Nome</span>
              </div>
              {% render_field form.name class+="form-control" %}
            </div>

            <!-- Slug -->
            <div class="input-group mb-3">
              <div class="input-group-prepend">
                <span class="input-group-text">Identificador</span>
              </div>
              {% render_field form.slug class+="form-control" %}
            </div>

            <button class="btn btn-primary">Enviar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/website/exclui.html
<!-- Estendemos do template base -->
{% extends "website/_layouts/base.html" %}

<!-- Bloco que define o <title></title> da nossa página -->
{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Funcionário</h5>

        <p class="card-text">
          Você tem certeza que quer excluir o funcionário
          <b>{{ funcionario.nome }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'website:lista_funcionarios' %}"
              class="btn btn-outline-danger">
                Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

website/templates/website/lista_comercios.html
{% extends "base.html" %}

{% block title %}Lista de Comércios{% endblock %}

{% load pagination %}
{% load l10n %}

{% block conteudo %}
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Comércio</h5>

          {% if comercios|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Comércios</code> cadastrados.
            </p>

            {% if success %}
                <p>Suas informações foram alteradas com sucesso</p>
            {% endif %}

            <table class="table table-striped table-bordered">
              <thead class="thead-dark">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Identificador</th>
                <th scope="col">Criado em</th>
                <th scope="col">Atualizado em</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for comercio in comercios %}
                <tr>
                  <th scope="row">{{ comercio.id }}</th>
                  <td>{{ comercio.name }}</td>
                  <td>{{ comercio.slug }}</td>
                  <td>{{ comercio.created_at|date:'d/m/Y' }}</td>
                  <td>{{ comercio.updated_at|date:'d/m/Y' }}</td>
                  <td>
                    <a href="{% url 'website:atualiza_comercio' slug=comercio.slug %}"
                       class="btn btn-info"><i class="fas fa-pen"></i>
                    </a>
                    <a href="{% url 'website:deleta_comercio' slug=comercio.slug  %}"
                      class="btn btn-outline-danger"><i class="fas fa-ban"></i>
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Comércio</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'website:cadastra_comercio' %}" class="btn btn-primary">
              Cadastrar Comércio
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <nav aria-label="Page navigation example">
        {% if is_paginated %}
          <ul class="pagination">
            {% if page_obj.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                  <span class="sr-only">Next</span>
                </a>
              </li>
            {% endif %}
            {% for i in paginator.page_range %}
              {% if page_obj.number == i %}
                <li class="page-item active">
                  <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
              {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                  <span class="sr-only">Next</span>
                </a>
              </li>
            {% endif %}
          </ul>
        {% endif %}
      </nav>
    </div>
  </div>
{% endblock %}

website/templates/website/lista_gastos.html
{% extends "base.html" %}

{% block title %}Lista Gastos{% endblock %}

{% load pagination %}
{% load l10n %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Gastos</h5>

          {% if gastos|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Gastos</code> cadastrados.
            </p>

            {% if success %}
                <p>Suas informações foram alteradas com sucesso</p>
            {% endif %}

            <table class="table table-striped table-bordered">
              <thead class="thead-dark">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Identificador</th>
                <th scope="col">Valor</th>
                <th scope="col">Data Gasto</th>
                <th scope="col">Comércio</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for gasto in gastos %}
                <tr>
                  <th scope="row">{{ gasto.id }}</th>
                  <td>{{ gasto.name }}</td>
                  <td>{{ gasto.slug }}</td>
                  <td>{{ gasto.valor }}</td>
                  <td>{{ gasto.datagasto|date:'d/m/Y' }}</td>
                  <td>{{ gasto.comercio.name }}</td>
                  <td>
                    <a href="{% url 'website:atualiza_gasto' pk=gasto.id %}"
                       class="btn btn-info" alt="editar"><i class="fas fa-pen"></i>
                    </a>
                    <a href="{% url 'website:deleta_gasto' pk=gasto.id %}"
                      class="btn btn-outline-danger"><i class="fas fa-ban"></i>
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Gasto</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'website:cadastra_gasto' %}" class="btn btn-primary">
              Cadastrar Gasto
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <nav aria-label="Page navigation example">
      {% if is_paginated %}
        <ul class="pagination">
          {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          {% endif %}
          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active">
                <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <a class="page-link" href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
              </a>
            </li>
          {% endif %}
        </ul>
      {% endif %}
    </nav>
  </div>
</div>
{# {% pagination request paginator page_obj %} #}
{% endblock %}

website/templates/website/lista_gastosPorComercio.html
{% extends "base.html" %}

{% block title %}Lista de Gastos por Comércio{% endblock %}

{% load pagination %}
{% load l10n %}

{% block conteudo %}
<div class="container">
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Lista de Gastos por Comércio</h5>

          {% if gastos|length > 0 %}
            <p class="card-text">
              Aqui está a lista de <code>Gastos</code> cadastrados.
            </p>

            {% if success %}
                <p>Suas informações foram alteradas com sucesso</p>
            {% endif %}

            <table class="table">
              <thead class="thead-dark">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Identificador</th>
                <th scope="col">Valor</th>
                <th scope="col">Data Gasto</th>
                <th scope="col">Comércio</th>
                <th scope="col" class="text-center">Ações</th>
              </tr>
              </thead>
              <tbody>
              {% for gasto in gastos %}
                <tr>
                  <td>{{ gasto.id }}</td>
                  <td>{{ gasto.name }}</td>
                  <td>{{ gasto.slug }}</td>
                  <td>{{ gasto.valor }}</td>
                  <td>{{ gasto.datagasto|date:'d/m/Y' }}</td>
                  <td>{{ gasto.comercio.name }}</td>
                  <td>
                    <a href="{% url 'website:atualiza_gasto' pk=gasto.id %}"
                       class="btn btn-info" alt="editar"><i class="fas fa-pen"></i>
                    </a>
                    <a href="{% url 'website:deleta_gasto' pk=gasto.id %}"
                      class="btn btn-outline-danger"><i class="fas fa-ban"></i>
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        {% else %}
          <div class="text-center mt-5 mb-5 jumbotron">
            <h5>Nenhum <code>Gasto</code> cadastrado ainda.</h5>
          </div>
        {% endif %}
          <hr />
          <div class="text-right">
            <a href="{% url 'website:cadastra_gasto' %}" class="btn btn-primary">
              Cadastrar Gasto
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% pagination request paginator page_obj %}
{% endblock %}