helloworld/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth.views import login, logout

from core import views

urlpatterns = [
    # URL padrão
    path('', views.index, name='index'),
    path('entrar/', login, {'template_name':'accounts/login.html'}, name='login'),
    path('sair/', logout, {'next_page':'index'}, name='logout'),
    path('conta/', include('accounts.urls')),
    path('website/', include('website.urls')),
    # Interface administrativa
    path('admin/', admin.site.urls),
]

website/urls.py
from website.views import (IndexTemplateView, ComercioListView,
    ComercioCreateView, ComercioUpdateView, ComercioDeleteView,
    GastoListView, GastoCreateView, GastoUpdateView,
    GastoDeleteView, GastoComercioListView)

from django.urls import path

app_name = "website"

urlpatterns = [
    path('',IndexTemplateView.as_view(),name="index"),
    path('gastos/',GastoListView.as_view(),name="lista_gastos"),
    path('gastosPorComercio/<slug>/',GastoComercioListView.as_view(),name="lista_gastosPorComercio"),
    path('gasto/cadastrar',GastoCreateView.as_view(),name="cadastra_gasto"),
    path('gasto/<pk>',GastoUpdateView.as_view(),name="atualiza_gasto"),
    path('gasto/excluir/<pk>',GastoDeleteView.as_view(),name="deleta_gasto"),
    path('comercios/',ComercioListView.as_view(),name="lista_comercios"),
    path('comercio/cadastrar',ComercioCreateView.as_view(),name="cadastra_comercio"),
    path('comercio/<slug>',ComercioUpdateView.as_view(),name="atualiza_comercio"),
    path('comercio/excluir/<slug>',ComercioDeleteView.as_view(),name="deleta_comercio"),
]

core/models.py
# coding=utf-8

from django.db import models

core/forms.py
# coding=utf-8

from django import forms
from django.core.mail import send_mail
from django.conf import settings


class ContactForm(forms.Form):

    name = forms.CharField(label='Nome')
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem', widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        message = self.cleaned_data['message']
        message = 'Nome: {0}\nE-mail:{1}\n{2}'.format(name, email, message)
        send_mail(
            'Contato do Django E-Commerce', message, settings.DEFAULT_FROM_EMAIL,
            [settings.DEFAULT_FROM_EMAIL]
        )

core/views.py
# coding=utf-8

from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import View, TemplateView, CreateView
from django.contrib.auth import get_user_model

User = get_user_model()

class IndexView(TemplateView):

    template_name = 'index.html'


index = IndexView.as_view()

core/templates/base.html
<!DOCTYPE html>
<html>
  {% load static tempo_atual %}

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Title -->
    <title>{% block title %}Sistema de Gerenciamento de Gastos{% endblock %}</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/png">

    <!-- Arquivos CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!-- Bloco de Estilos -->
    {% block styles %}{% endblock %}
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">
          <img src="{% static 'img/favicon.png' %}" height='45px'>
        </a>
        <button class="navbar-toggler" type="button"
            data-toggle="collapse" data-target="#conteudo-navbar"
            aria-controls="conteudo-navbar" aria-expanded="false"
            aria-label="Ativar navegação">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="conteudo-navbar">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown"
                href="{% url 'website:lista_gastos' %}" id="download">Comércios<span class="caret"></span></a>
                <ul class="dropdown-menu" aria-labelledby="download">
                {% for comercio in comercios %}
                  <li><a href="{{ comercio.get_absolute_url }}">{{ comercio }}</a></li>
                {% endfor %}
                </ul>
              </li>
              <li class="nav-item">
                  <a class="nav-link"
                    href="{% url 'website:lista_gastos' %}">Gasto</a>
              </li>
              </li>
              <li class="nav-item">
              </li>
          </ul>
          <ul class="navbar-nav float-right">
            <li class="nav-item">
                <!-- Aqui está nosso filtro -->
                <a class="nav-link" href="#">
                  <b>Hora: </b>{% tempo_atual %}
                </a>
            </li>
          </ul>
          <ul class="nav nav-pills nav-fill float-right">
            <li class="nav-item">
              {% if user.is_authenticated %}
                <li><a class="nav-link active" href="{% url 'logout' %}">Sair</a></li>
              {% else %}
                <li><a class="nav-link active" href="{% url 'login' %}">Entrar</a></li>
              {% endif %}
            </li>
          </ul>
        </div>
    </nav>
    <div class="container margin-top">
    {% block messages %}
      {% for message in messages  %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
      {% endfor %}
    {% endblock %}
    <!-- Bloco de conteúdo -->
    <div class="card text-center">
      <div class="card-body">
        
        {% block conteudo %}{% endblock %}
      </div>
      <nav class="navbar navbar-expand-lg fixed-bottom navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Gerenciamento de Gastos</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="#">Home<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="#">Produtos</a>
            <a class="nav-item nav-link" href="#">Contato</a>
            <a class="nav-item nav-link disabled" href="#">Termos e Privacidade</a>
          </div>
        </div>
      </nav>
    </div>


    <!-- Arquivos necessários para o Bootstrap -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- Bloco de scripts -->
    {% block scripts %}{% endblock %}

    <!-- Scripts.js -->
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>

core/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}Página Inicial{% endblock %}

<!-- Bloco de conteúdo da nossa página -->
{% block conteudo %}
  <br /><br />
  <div class="text-center">
    <h1 class="card-title">Gerenciamento de Gastos</h1>
    <figure class="figure">
      <img src="{% static 'img/img_fundo.jpg' %}"
          class="img-fluid rounded mx-auto d-block" alt="Responsive image">
    </figure>
  </div>
{% endblock %}

core/templates/login.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}Entrar | {{ block.super }}{% endblock  %}

{% block container %}
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="page-header">
            <h1>Entrar</h1>
        </div>
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            {% for error in form.non_field_errors  %}
                <div class="alert alert-danger">
                  {{ error }}
                </div>
            {% endfor %}
            <fieldset>
                <div class="form-group{% if form.username.errors %} has-error{% endif %}">
                  <label for="{{ form.username.auto_id }}"
                          class="col-md-3 control-label">{{ form.username.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.username class="form-control" %}
                    {% for error in form.username.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group{% if form.password.errors %} has-error{% endif %}">
                  <label for="{{ form.password.auto_id }}"
                          class="col-md-3 control-label">{{ form.password.label }}</label>
                  <div class="col-md-9">
                    {% render_field form.password class="form-control" %}
                    {% for error in form.password.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                  </div>
                </div>
                <div class="form-group">
                  <div class="col-md-9 col-md-offset-3">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                  </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock  %}